In [1]:
import numpy as np
# import matplotlib.pyplot as plt
# import scipy
# import sympy as sp
# import pandas as pd

***

#### Выполнить QR - разложение матрицы A, получив матрицу R и матрицу T, являющуюся обратной к Q. Вычисления организовать для произвольной квадратной матрицы порядка n.

***

### Постановка задачи

<u>Цель</u>: получить разложение матрицы A на матрицу R и матрицу T, обратную к Q.

<u>Исходные данные</u>: Матрица A размера NxN.

<u>Модельные представления</u>: QR-разложение представляет исходную матрицу в виде произведения двух матриц: Q - ортогональная матрица, R - верхнетреугольная матрица.

<u>Критерий оценки результата</u>: выполняются равенства A = $ QR, QT = E $.

***

In [3]:
# Задаем матрицу A
A = np.array([
    [4.33958, 0.833874, 0.461316, 0.483263, 0.952033, 0.60669],
    [0.122425, 4.0698, 0.884887, 0.309651, 0.0898522, 0.931766],
    [0.160705, 0.050313, 3.16855, 0.874556, 0.125428, 0.868234],
    [0.715778, 0.634697, 0.394662, 2.88133, 0.097117, 0.214019],
    [0.795368, 0.902429, 0.711462, 0.268238, 5.44945, 0.0279822],
    [0.420162, 0.0779385, 0.510535, 0.48501, 0.0974471, 5.09599]
])

In [80]:
def qr_decomposition(A):
    n = A.shape[0]
    R = A.copy()
    Q = np.eye(n)

    for k in range(n - 1):
        for l in range(k + 1, n):
            # Вычисляем c и s
            R_kk = R[k, k]
            R_lk = R[l, k]
            magnitude = np.sqrt(R_kk**2 + R_lk**2)
            c = R_kk / magnitude
            s = R_lk / magnitude

            # Создаем матрицу преобразования T_lk
            T_lk = np.eye(n)
            T_lk[k, k] = c
            T_lk[l, k] = -s
            T_lk[k, l] = s
            T_lk[l, l] = c

            # Обновляем матрицу R и матрицу Q
            R = np.dot(T_lk, R)
            Q = np.dot(Q, T_lk.T)

    return Q, R

In [81]:
Q, R = qr_decomposition(A)

In [86]:
display(np.dot(Q, R))

array([[4.33958  , 0.833874 , 0.461316 , 0.483263 , 0.952033 , 0.60669  ],
       [0.122425 , 4.0698   , 0.884887 , 0.309651 , 0.0898522, 0.931766 ],
       [0.160705 , 0.050313 , 3.16855  , 0.874556 , 0.125428 , 0.868234 ],
       [0.715778 , 0.634697 , 0.394662 , 2.88133  , 0.097117 , 0.214019 ],
       [0.795368 , 0.902429 , 0.711462 , 0.268238 , 5.44945  , 0.0279822],
       [0.420162 , 0.0779385, 0.510535 , 0.48501  , 0.0974471, 5.09599  ]])

In [20]:
display(A)

array([[4.33958  , 0.833874 , 0.461316 , 0.483263 , 0.952033 , 0.60669  ],
       [0.122425 , 4.0698   , 0.884887 , 0.309651 , 0.0898522, 0.931766 ],
       [0.160705 , 0.050313 , 3.16855  , 0.874556 , 0.125428 , 0.868234 ],
       [0.715778 , 0.634697 , 0.394662 , 2.88133  , 0.097117 , 0.214019 ],
       [0.795368 , 0.902429 , 0.711462 , 0.268238 , 5.44945  , 0.0279822],
       [0.420162 , 0.0779385, 0.510535 , 0.48501  , 0.0974471, 5.09599  ]])

In [85]:
display(Q.T @ Q)

array([[ 1.00000000e+00, -1.27878033e-17, -2.54405815e-17,
        -5.00345895e-17, -4.61359157e-17,  5.12634636e-19],
       [-1.27878033e-17,  1.00000000e+00, -6.84828623e-18,
        -4.72917376e-17, -9.01403883e-17,  9.66432540e-18],
       [-2.54405815e-17, -6.84828623e-18,  1.00000000e+00,
        -1.45950433e-17, -2.99523384e-17, -1.23133553e-16],
       [-5.00345895e-17, -4.72917376e-17, -1.45950433e-17,
         1.00000000e+00,  1.30098580e-17,  1.83548843e-17],
       [-4.61359157e-17, -9.01403883e-17, -2.99523384e-17,
         1.30098580e-17,  1.00000000e+00,  1.05255508e-17],
       [ 5.12634636e-19,  9.66432540e-18, -1.23133553e-16,
         1.83548843e-17,  1.05255508e-17,  1.00000000e+00]])

***

2. Дайте определение понятия нормы элемента в некотором линейном пространстве. Как можно использовать норму элемента для вычисления расстояния между элементами в этом пространстве.

Норма элемента в линейном пространстве - это функция, которая сопоставляет элементу этого пространства неотрицательное вещественное число и удовлетворяет следующим условиям:

1. Норма нулевого элемента равна нулю: ||0|| = 0.
2. Норма элемента, умноженного на скаляр, равна модулю этого скаляра, умноженному на норму элемента: ||αx|| = |α| * ||x||, где α - скаляр.
3. Неравенство треугольника: ||x + y|| <= ||x|| + ||y||, где x и y - элементы линейного пространства.

Норма элемента используется для измерения "размера" или "длины" элемента в данном пространстве. Это понятие позволяет определить расстояние между элементами в линейном пространстве, используя норму разности двух элементов. Расстояние между элементами x и y можно определить как норму их разности:

$$ d(x,y)=∣∣x−y∣∣ $$

Это расстояние измеряет, насколько "близки" или "далеки" элементы x и y в данном линейном пространстве, и оно полезно, например, при решении задач оптимизации, поиске ближайших соседей в машинном обучении и других приложениях.

***

4.	Что такое вектор невязки для СЛАУ и как определить его норму?

Вектор невязки для системы линейных алгебраических уравнений (СЛАУ) представляет собой вектор, который показывает, насколько близко полученное решение приближается к удовлетворению всех уравнений системы. Если система имеет вид:

$$ Ax = b, $$

где A - матрица коэффициентов, x - вектор неизвестных, b - вектор правых частей, то вектор невязки для этой системы определяется как:

$$ r = Ax - b $$

Чтобы определить норму вектора можно воспользоваться формулой:

$$ ||r||_2 = \sum_{i=1}^{n}|r_i| $$

***

6.	Пусть получено LU разложение для некоторой квадратной матрицы A. Как можно использовать его для получения решения системы Ax=b?

В результате разложения матрицы начальная система уравнений эквивалентна двум системам

$$ Ax = b => \\ LUx = b => \\ Ux = z => \\ Lz = b $$

Для определения вектора x (решения исходной системы) воспользуемся треугольным видом матрицы U и определим:

$$ x_n = \frac{z_n}{U_{nn}} $$

Далее для $ k = n-1, n-2, \dots, 1 $ определяем остальные компоненты:

$$ x_k = \frac{z_k - \sum_{i=k+1}^{n} U_{ki} x_i}{U_{kk}} $$

Найденный вектор x является решением исходной системы уравнений Ax = b.